sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t aspetter/docker-react .

script:
    - docker run -e CI=true aspetter/docker-react npm run test