sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -f -t aspetter/docker-react Dockerfile.dev .

script:
    - docker run -e CI=true aspetter/docker-react npm run test